import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Navbar from "./Components/Navbar";

const patriot = localFont({
  src: "./fonts/patriotVF.otf",
  variable: "--font-patriot",
  weight: "100 200 300 400 500 600 700 800 900",
});
const rufina = localFont({
  src: "./fonts/rufinaVF.ttf",
  variable: "--font-rufina",
  weight: "100 200 300 400 500 600 700 800 900",
});

const oxygen = localFont({
  src: "./fonts/oxygenVF.ttf",
  variable: "--font-oxygen",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Pantone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${patriot.variable} ${rufina.variable} ${oxygen.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
